import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const source=await fs.readFile(new URL('../web/preferences-state.js',import.meta.url),'utf8');
const {createPreferences,editableValues,applyCard,changeMake,parseInteger,preferenceErrors,payload,summaryPairs}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const directory=JSON.parse(await fs.readFile(new URL('../ua_order/preferences.json',import.meta.url),'utf8'));
directory.current_year=new Date().getUTCFullYear();
const catalog=JSON.parse(await fs.readFile(new URL('../../ua_order_ge_8country_guard_016/country_models.json',import.meta.url),'utf8'));
for(const [country,data] of Object.entries(catalog.countries))for(const card of data.models){
 const state=applyCard(createPreferences(),country,card.key,directory.card_presets[card.key]);
 assert.equal(state.values.purchase_country_code,country);
 assert.equal(state.values.budget.max,null);assert.equal(state.values.mileage.max,null);assert.equal(state.values.colours,null);
 assert.equal(state.values.customer_name,'');assert.equal(state.values.delivery_country,'');
 if(card.key!=='classics-1980-1990') assert.ok(state.values.models.every(m=>directory.makes[state.values.make].models.includes(m)));
 else assert.deepEqual(state.values.year,{from:1980,to:1990,any:false});
}
let state=applyCard(createPreferences(),'korea','kia-k5',directory.card_presets['kia-k5']);
Object.assign(state.values,{customer_name:'Олег',contact:{method:'telegram',value:'@test_user'},delivery_country:'georgia',delivery_city:{code:'tbilisi',other:''},comment:'Сохранить пожелания'});
state.values.budget={mode:'limit',max:17000,currency:'USD'};state.dirty.budget=true;
state.values.colours=['white'];state.dirty.colours=true;
state.values.year={from:null,to:null,any:false};state.dirty.year=true;
changeMake(state,'toyota',directory);state.values.models=['Camry'];
const unchanged=applyCard(state,'korea','kia-k5',directory.card_presets['kia-k5']);
assert.deepEqual(unchanged,state,'same card must preserve a manually replaced make');
let changed=applyCard(state,'korea','hyundai-sonata',directory.card_presets['hyundai-sonata']);
assert.equal(changed.values.make,'hyundai');assert.deepEqual(changed.values.models,['Sonata']);
for(const key of ['customer_name','contact','delivery_country','delivery_city','comment','budget','colours','year'])assert.deepEqual(changed.values[key],state.values[key],key);
state=applyCard(createPreferences(),'japan','classics-1980-1990',directory.card_presets['classics-1980-1990']);
state=applyCard(state,'korea','kia-k5',directory.card_presets['kia-k5']);
assert.deepEqual(state.values.year,{from:null,to:null,any:false},'missing new data clears old automatic values');
changeMake(state,'kia',directory);assert.deepEqual(state.values.models,['K5']);
changeMake(state,'toyota',directory);assert.deepEqual(state.values.models,[]);assert.equal(state.values.model_mode,'selected');
changeMake(state,'help',directory);assert.equal(state.values.model_mode,'help');
changeMake(state,'other',directory);assert.equal(state.values.model_mode,'other');
for(const value of ['109353','109 353','109.353','109,353',109353])assert.equal(parseInteger(value),109353);
for(const value of ['109.3','109,35','1 09 353','1.000,000',-1,true,[],null])assert.equal(parseInteger(value),null);
const empty=preferenceErrors(createPreferences().values,directory);for(const key of ['year','mileage','make','models','budget','contact','delivery_country'])assert.ok(empty[key]);
const values=changed.values;
Object.assign(values,{year:{from:2015,to:2022,any:false},mileage:{max:'109,353',any:false},vehicle_type:'sedan',fuel:['hybrid'],drive:['fwd'],engine:{from:'1,5',to:2},purchase_timing:'month'});
assert.deepEqual(preferenceErrors(values,directory),{});
const oldDraft=structuredClone(values);oldDraft.priority={make:'required_for_search',year:'required_for_search'};oldDraft.year.any=true;
const snapshot=structuredClone(oldDraft),editable=editableValues(oldDraft);
assert.deepEqual(editable.priority,{});assert.deepEqual(editable.year,{from:2015,to:2022,any:false});
assert.deepEqual(editable.colours,values.colours);assert.equal(editable.comment,values.comment);
assert.deepEqual(oldDraft,snapshot,'an uncertain legacy request must not be mutated');
const anyDraft={...oldDraft,model_mode:'any',models:[]};
assert.equal(editableValues(anyDraft).model_mode,'selected');
assert.equal(anyDraft.model_mode,'any','legacy requests remain unchanged');
assert.ok(preferenceErrors(editableValues(anyDraft),directory).models,'a retired any-model draft must require a model');
assert.ok(preferenceErrors(anyDraft,directory).models);
assert.equal(editableValues({...anyDraft,make:'other'}).model_mode,'other');
assert.equal(editableValues({...anyDraft,make:'other',model_mode:''}).model_mode,'other');
assert.ok(preferenceErrors({...oldDraft,year:{from:null,to:null,any:true}},directory).year);
for(const lang of ['ru','uk','ka']){
 const result=payload(oldDraft,catalog,directory,lang,'uuid','consent-v1',true);
 assert.equal(result.make,'hyundai');assert.deepEqual(result.models,['Sonata']);assert.equal(result.mileage.max,109353);assert.equal(result.preferences.criteria.engine.from,1.5);
 assert.equal(result.preferences.schema_version,1);assert.equal('engine' in result,false);assert.equal('priority' in result,false);
 assert.deepEqual(result.preferences.priority,{});assert.equal(result.year.any,false);
 assert.ok(summaryPairs(result,catalog,directory,lang).some(([k,v])=>v.includes('Sonata')));
 assert.ok(summaryPairs(result,catalog,directory,lang).some(([k,v])=>v===directory.options.colours.white[lang]));
}
console.log('PASS: all 40 cards, explicit missing values, manual clearing, same/new card, make/model dependency, numeric precision, three languages and final edited payload');
