"""Exact selected safe function excerpts for isolated tests; no whole private modules."""

FIXTURES = {'contract': 'UA0022-SAFE-SELECTED-FUNCTION-FIXTURES-1',
 'description': 'Exact selected function excerpts, no complete private runtime modules. '
                'Rendering/DB/network dependencies are stubbed by tests. Original whole-source '
                'hashes are provenance, not a deployment fixture.',
 'sources': {'cars_ui.py': {'functions': [{'ast_sha256': '7fb461cb4a25b6ed8a0f3593f80135b04c32bf861abf734a1b59d41af06406df',
                                           'extracted_sha256': '19ec0c4e8136870410e2bb1693fa22abf3d616202468afa7e40fbf3e9d34bc0d',
                                           'function': '_peresobrat_stranicy',
                                           'occurrence': 0,
                                           'original_end_line': 3202,
                                           'original_start_line': 3188,
                                           'source': 'def _peresobrat_stranicy():\n'
                                                     '    """Страницы сайта после удаления — иначе '
                                                     'там останется старое."""\n'
                                                     '    try:\n'
                                                     '        import sys as _s\n'
                                                     '        if "/home/Carix" not in _s.path:\n'
                                                     '            _s.path.insert(0, '
                                                     '"/home/Carix")\n'
                                                     '        import importlib as _i\n'
                                                     '        import stranica as _st\n'
                                                     '        _i.reload(_st)\n'
                                                     '        if hasattr(_st, "main"):\n'
                                                     '            _st.main()\n'
                                                     '            return True\n'
                                                     '    except Exception as e:\n'
                                                     '        log.warning("Пересборка страниц: '
                                                     '%s", e)\n'
                                                     '    return False\n'}],
                            'original_source_sha256': '4c00512c56ee19ccda4ff0086aa696facf8aeea013c894168007c78c9490adde'},
             'publikaciya.py': {'functions': [{'ast_sha256': '79013b6281f368b4ae66cc2923dbcddf68212f88b246e5a292145154a628e5fc',
                                               'extracted_sha256': '5daee5d1f127f6195abe2af9f45ae008c6e3cc89d5cb1c00b4f01870a15a27d6',
                                               'function': '_sha',
                                               'occurrence': 0,
                                               'original_end_line': 28,
                                               'original_start_line': 20,
                                               'source': 'def _sha(put):\n'
                                                         '    try:\n'
                                                         '        h = hashlib.sha256()\n'
                                                         '        with open(put, "rb") as f:\n'
                                                         '            for k in iter(lambda: '
                                                         'f.read(65536), b""):\n'
                                                         '                h.update(k)\n'
                                                         '        return h.hexdigest()\n'
                                                         '    except Exception:\n'
                                                         '        return "-"\n'},
                                              {'ast_sha256': '4f24136494563a37ef5d1e75fb473208f7166577925480aab8851848f251f9bc',
                                               'extracted_sha256': 'f5a6e942658e143574b3b3a50da35da5189fdede82a454268229c1797312b5af',
                                               'function': '_kartochki',
                                               'occurrence': 0,
                                               'original_end_line': 66,
                                               'original_start_line': 54,
                                               'source': 'def _kartochki(krome=None):\n'
                                                         '    """sha всех карточек и диагностик, '
                                                         'кроме указанной машины."""\n'
                                                         '    d = {}\n'
                                                         '    for papka in (VIDEO, SITE):\n'
                                                         '        if not os.path.isdir(papka):\n'
                                                         '            continue\n'
                                                         '        for imya in os.listdir(papka):\n'
                                                         '            if not '
                                                         '(imya.startswith("UA-") and '
                                                         'imya.endswith(".html")):\n'
                                                         '                continue\n'
                                                         '            if krome and '
                                                         'imya.startswith(krome):\n'
                                                         '                continue\n'
                                                         '            d[os.path.join(papka, imya)] '
                                                         '= _sha(os.path.join(papka, imya))\n'
                                                         '    return d\n'},
                                              {'ast_sha256': '7653af9fb94a8edfc30cb51c356b4e629510c4a52199ae29375c0520c40591d2',
                                               'extracted_sha256': '27f3422fc4025ff1baadd177e82f0a5a52e20cbd533cc8c667a1ef476730e4c9',
                                               'function': 'opublikovat',
                                               'occurrence': 0,
                                               'original_end_line': 220,
                                               'original_start_line': 149,
                                               'source': 'def opublikovat(kod, proba=False):\n'
                                                         '    """Единственная разрешённая '
                                                         'публикация карточки. (ok, текст для '
                                                         'владельца)"""\n'
                                                         '    kod = (kod or "").strip().upper()\n'
                                                         '    if not re.match(r"^UA-\\d{3,5}$", '
                                                         'kod):\n'
                                                         '        return False, "Публикация '
                                                         'отменена: непонятный номер машины."\n'
                                                         '\n'
                                                         '    do = _kartochki(krome=kod)          '
                                                         '# чужие карточки до работы\n'
                                                         '    try:\n'
                                                         '        html, diag, m = _master(kod)\n'
                                                         '    except Exception as e:\n'
                                                         '        _zhurnal(["%s FAIL сборка '
                                                         'мастером: %s" % (kod, e)])\n'
                                                         '        return False, "Публикация '
                                                         'отменена: сборщик не смог собрать %s '
                                                         '(%s). Старая страница цела." % (kod, e)\n'
                                                         '    if not html:\n'
                                                         '        _zhurnal(["%s FAIL машина не '
                                                         'найдена в CRM" % kod])\n'
                                                         '        return False, "Публикация '
                                                         'отменена: %s не найдена среди машин '
                                                         'CRM." % kod\n'
                                                         '\n'
                                                         '    prichiny = proverit(html, kod)\n'
                                                         '    if prichiny:\n'
                                                         '        _zhurnal(["%s FAIL валидация: '
                                                         '%s" % (kod, "; ".join(prichiny))])\n'
                                                         '        return False, ("Публикация '
                                                         'отменена, страница не прошла '
                                                         'проверку:\\n· %s\\n"\n'
                                                         '                       "Прежняя страница '
                                                         'на сайте не тронута." % "\\n· '
                                                         '".join(prichiny))\n'
                                                         '\n'
                                                         '    if proba:\n'
                                                         '        return True, "Проба: страница %s '
                                                         'собрана и проверена, ничего не '
                                                         'записано." % kod\n'
                                                         '\n'
                                                         '    papka_rez = '
                                                         'os.path.join(REZERV_KORE, "%s_%s" % '
                                                         '(kod, time.strftime("%Y%m%d_%H%M%S")))\n'
                                                         '    celi = []\n'
                                                         '    for papka in (VIDEO, SITE):\n'
                                                         '        if not os.path.isdir(papka):\n'
                                                         '            continue\n'
                                                         '        celi.append(os.path.join(papka, '
                                                         'kod + ".html"))\n'
                                                         '        for imya in os.listdir(papka):\n'
                                                         '            if '
                                                         're.match(r"^%s-[0-9a-f]{6,10}\\.html$" % '
                                                         'kod, imya):\n'
                                                         '                '
                                                         'celi.append(os.path.join(papka, imya))\n'
                                                         '        if diag:\n'
                                                         '            '
                                                         'celi.append(os.path.join(papka, kod + '
                                                         '"-diag.html"))\n'
                                                         '    try:\n'
                                                         '        os.makedirs(papka_rez, '
                                                         'exist_ok=True)\n'
                                                         '        for put in celi:\n'
                                                         '            if os.path.exists(put):\n'
                                                         '                shutil.copy2(put, '
                                                         'os.path.join(\n'
                                                         '                    papka_rez, '
                                                         'put.replace(BASE + "/", "").replace("/", '
                                                         '"__")))\n'
                                                         '    except Exception as e:\n'
                                                         '        _zhurnal(["%s FAIL резерв: %s" % '
                                                         '(kod, e)])\n'
                                                         '        return False, "Публикация '
                                                         'отменена: не удалось сделать резерв '
                                                         '(%s)." % e\n'
                                                         '\n'
                                                         '    bylo = dict((put, _sha(put)) for put '
                                                         'in celi)\n'
                                                         '    try:\n'
                                                         '        for put in celi:\n'
                                                         '            _zapisat_atomarno(put, diag '
                                                         'if put.endswith("-diag.html") else '
                                                         'html)\n'
                                                         '    except Exception as e:\n'
                                                         '        _otkat(papka_rez, celi)\n'
                                                         '        _zhurnal(["%s FAIL запись: %s — '
                                                         'выполнен откат" % (kod, e)])\n'
                                                         '        return False, "Публикация '
                                                         'отменена при записи (%s). Выполнен '
                                                         'откат." % e\n'
                                                         '\n'
                                                         '    posle = _kartochki(krome=kod)\n'
                                                         '    izmenilis = [k for k in do if '
                                                         'do.get(k) != posle.get(k)]\n'
                                                         '    if izmenilis:\n'
                                                         '        _otkat(papka_rez, celi)\n'
                                                         '        _zhurnal(["%s FAIL регрессия: '
                                                         'изменились %s — откат" % (kod, ", '
                                                         '".join(izmenilis))])\n'
                                                         '        return False, ("Публикация '
                                                         'отменена: изменились чужие карточки '
                                                         '(%s). "\n'
                                                         '                       "Выполнен откат." '
                                                         '% ", ".join(os.path.basename(x) for x in '
                                                         'izmenilis))\n'
                                                         '\n'
                                                         '    stalo = dict((put, _sha(put)) for '
                                                         'put in celi)\n'
                                                         '    _zhurnal(["%s PASS публикация · '
                                                         'мастер stranica.sobrat_kartochku · '
                                                         'файлов %d"\n'
                                                         '              % (kod, len(celi))]\n'
                                                         '             + ["    %s  %s -> %s" % '
                                                         '(os.path.basename(k), (bylo.get(k) or '
                                                         '"-")[:12],\n'
                                                         '                                      '
                                                         '(stalo.get(k) or "-")[:12]) for k in '
                                                         'celi])\n'
                                                         '    hvost = "" if diag else '
                                                         '"\\nМатериалов диагностики в CRM нет — '
                                                         'страница диагностики не трогалась."\n'
                                                         '    return True, ("Страница %s обновлена '
                                                         'на сайте по утверждённому '
                                                         'шаблону.%s\\n"\n'
                                                         '                  '
                                                         '"https://www.uaart.com.ua/video/%s.html?v=%d"\n'
                                                         '                  % (kod, hvost, kod, '
                                                         'int(time.time())))\n'},
                                              {'ast_sha256': '253f3a35224d5a55d9ab9d52c1c22a265ea01d2eda7a809484fc34a99cda718c',
                                               'extracted_sha256': '44564fb9e0c7b7d026aada7746077f9b840a50141e5324e62c5cd4c7eaa35841',
                                               'function': '_otkat',
                                               'occurrence': 0,
                                               'original_end_line': 230,
                                               'original_start_line': 223,
                                               'source': 'def _otkat(papka_rez, celi):\n'
                                                         '    for put in celi:\n'
                                                         '        kopiya = os.path.join(papka_rez, '
                                                         'put.replace(BASE + "/", "").replace("/", '
                                                         '"__"))\n'
                                                         '        try:\n'
                                                         '            if os.path.exists(kopiya):\n'
                                                         '                shutil.copy2(kopiya, '
                                                         'put)\n'
                                                         '        except Exception:\n'
                                                         '            pass\n'}],
                                'original_source_sha256': '296c389b477472032bad714e41f12bfa4b7e47ad784ac6900ba55f136d939c72'},
             'publish_transaction_guard.py': {'functions': [{'ast_sha256': '629f9db2d407bdaddff66d83a7f85ffa3a9b74973e66e4de0498f6cc6ae763b9',
                                                             'extracted_sha256': '6a6d3b92c2190ba7fa31b400b620e604534babc756db016624d635ba3175b6d0',
                                                             'function': '_exclusive_lock',
                                                             'occurrence': 0,
                                                             'original_end_line': 229,
                                                             'original_start_line': 210,
                                                             'source': '@contextlib.contextmanager\n'
                                                                       'def _exclusive_lock():\n'
                                                                       '    '
                                                                       'LOCK.parent.mkdir(parents=True, '
                                                                       'exist_ok=True)\n'
                                                                       '    handle = open(LOCK, '
                                                                       '"a+")\n'
                                                                       '    deadline = '
                                                                       'time.monotonic() + '
                                                                       'WAIT_SECONDS\n'
                                                                       '    try:\n'
                                                                       '        while True:\n'
                                                                       '            try:\n'
                                                                       '                '
                                                                       'fcntl.flock(handle.fileno(), '
                                                                       'fcntl.LOCK_EX | '
                                                                       'fcntl.LOCK_NB)\n'
                                                                       '                break\n'
                                                                       '            except '
                                                                       'BlockingIOError:\n'
                                                                       '                if '
                                                                       'time.monotonic() >= '
                                                                       'deadline:\n'
                                                                       '                    raise '
                                                                       'PublishError("PUBLISH_LOCK_TIMEOUT")\n'
                                                                       '                '
                                                                       'time.sleep(0.25)\n'
                                                                       '        yield\n'
                                                                       '    finally:\n'
                                                                       '        try:\n'
                                                                       '            '
                                                                       'fcntl.flock(handle.fileno(), '
                                                                       'fcntl.LOCK_UN)\n'
                                                                       '        finally:\n'
                                                                       '            '
                                                                       'handle.close()\n'}],
                                              'original_source_sha256': '3d80712290e0881ebe7583231b532de422f808e6f18b5f6a90566d9e1eed3e0d'},
             'stranica.py': {'functions': [{'ast_sha256': '5c5564c9b1d2fd965e2e7d35aa3757290d7b54998dd968dbbbf476cfa68f3277',
                                            'extracted_sha256': '8633f52c3c4cdb5ef5a4ee9d487dbb64e4b2281201e3013273526e3a09b0fa2b',
                                            'function': 'main',
                                            'occurrence': 0,
                                            'original_end_line': 1922,
                                            'original_start_line': 1836,
                                            'source': 'def main():\n'
                                                      '    print("СБОРКА СТРАНИЦ UA ART — %s" % '
                                                      'time.strftime("%d.%m.%Y %H:%M"))\n'
                                                      '    print()\n'
                                                      '    staroe = otklyuchit_staroe()\n'
                                                      '    if staroe:\n'
                                                      '        print("выключено: %s" % ", '
                                                      '".join(staroe))\n'
                                                      '        print()\n'
                                                      '    try:\n'
                                                      '        spisok = mashiny()\n'
                                                      '    except Exception:\n'
                                                      '        print("Не читается база:")\n'
                                                      '        '
                                                      'print(traceback.format_exc(limit=2))\n'
                                                      '        return\n'
                                                      '\n'
                                                      '    try:\n'
                                                      '        from PIL import Image  # noqa\n'
                                                      '        szhatie = True\n'
                                                      '    except Exception:\n'
                                                      '        szhatie = False\n'
                                                      '        print("ВНИМАНИЕ: библиотека Pillow '
                                                      'недоступна — фото пойдут в полном '
                                                      'размере,")\n'
                                                      '        print("страницы будут грузиться '
                                                      'медленно. Поставьте её один раз в '
                                                      'консоли:")\n'
                                                      '        print("  pip3.10 install --user '
                                                      'Pillow")\n'
                                                      '        print()\n'
                                                      '\n'
                                                      '    kadry_po_nomeru = {}\n'
                                                      '    legkie_po_nomeru = {}\n'
                                                      '    bylo_vsego = stalo_vsego = 0\n'
                                                      '    for m in spisok:\n'
                                                      '        nom = nomer(m)\n'
                                                      '        kadry = kadry_mashiny(m)\n'
                                                      '        kadry_po_nomeru[nom] = kadry\n'
                                                      '        if kadry:\n'
                                                      '            sredn, mal = legkie(kadry)\n'
                                                      '            legkie_po_nomeru[nom] = (sredn, '
                                                      'mal)\n'
                                                      '            bylo_vsego += ves(kadry)\n'
                                                      '            stalo_vsego += ves(sredn)\n'
                                                      '        else:\n'
                                                      '            sredn = []\n'
                                                      '            print("  %s — без фотографий, '
                                                      'страница собрана с одним текстом" % nom)\n'
                                                      '        html = sobrat_kartochku(m, kadry, '
                                                      'sredn)\n'
                                                      '        skolko = zapisat(nom, html)\n'
                                                      '        v_zamke = obnovit_etalon(nom, '
                                                      'html)\n'
                                                      '        if est_diagnostika(m):\n'
                                                      '            diag = sobrat_diagnostiku(m)\n'
                                                      '            zapisat(nom + "-diag", diag)\n'
                                                      '            obnovit_etalon(nom + "-diag", '
                                                      'diag)\n'
                                                      '            df, dv = kadry_diagnostiki(m)\n'
                                                      '            print("  %s — диагностика: фото '
                                                      '%d · видео %d · отчёт %s"\n'
                                                      '                  % (nom, len(df), len(dv), '
                                                      '"есть" if (m.get("diag_link") or '
                                                      '"").strip() else "нет"))\n'
                                                      '        video = "есть" if '
                                                      'os.path.exists(os.path.join(PAPKA_VID, nom '
                                                      '+ ".mp4")) else "нет"\n'
                                                      '        print("  %s — %s · фото %d · видео '
                                                      '%s · %s · копий %d%s"\n'
                                                      '              % (nom, cena(m), len(kadry), '
                                                      'video, etap_korotko(m), skolko,\n'
                                                      '                 (" · в замке %d" % '
                                                      'v_zamke) if v_zamke else ""))\n'
                                                      '\n'
                                                      '    katalog = sobrat_katalog(spisok, '
                                                      'kadry_po_nomeru, legkie_po_nomeru)\n'
                                                      '    skolko = zapisat("katalog", katalog)\n'
                                                      '    obnovit_etalon("katalog", katalog)\n'
                                                      '    print("  каталог — машин %d · копий %d" '
                                                      '% (len(spisok), skolko))\n'
                                                      '\n'
                                                      '    glavnaya = sobrat_glavnuyu(spisok, '
                                                      'kadry_po_nomeru, legkie_po_nomeru)\n'
                                                      '    zapisat("index", glavnaya)\n'
                                                      '    obnovit_etalon("index", glavnaya)\n'
                                                      '    print("  главная — собрана")\n'
                                                      '\n'
                                                      '    for imya, sbor in (("podbor", '
                                                      'sobrat_podbor), ("info", sobrat_info)):\n'
                                                      '        stranica = sbor()\n'
                                                      '        zapisat(imya, stranica)\n'
                                                      '        obnovit_etalon(imya, stranica)\n'
                                                      '    print("  подбор и условия — собраны")\n'
                                                      '\n'
                                                      '    if bylo_vsego and szhatie:\n'
                                                      '        print()\n'
                                                      '        print("  фото облегчены: %d МБ → %d '
                                                      'МБ (в %.0f раз легче)"\n'
                                                      '              % (bylo_vsego // 1048576, '
                                                      'max(stalo_vsego // 1048576, 1),\n'
                                                      '                 bylo_vsego / '
                                                      'max(stalo_vsego, 1)))\n'
                                                      '\n'
                                                      '    print()\n'
                                                      '    print("ССЫЛКИ")\n'
                                                      '    metka = int(time.time())\n'
                                                      '    print("  ГЛАВНАЯ:  %s/index.html?v=%d" '
                                                      '% (sajt(), metka))\n'
                                                      '    print("  каталог:  '
                                                      '%s/katalog.html?v=%d" % (sajt(), metka))\n'
                                                      '    print("  подбор:   %s/podbor.html?v=%d" '
                                                      '% (sajt(), metka))\n'
                                                      '    print("  условия:  %s/info.html?v=%d" % '
                                                      '(sajt(), metka))\n'
                                                      '    for m in spisok:\n'
                                                      '        print("  карточка: %s/%s.html?v=%d" '
                                                      '% (sajt(), nomer(m), metka))\n'
                                                      '    print()\n'
                                                      '    print("Готово. Перезапускать бота не '
                                                      'нужно — страницы уже обновлены.")\n'},
                                           {'ast_sha256': '269fb364c1ad92c6038f6c2ef85f3663798055283eb5b1701ed890a3938def66',
                                            'extracted_sha256': 'cda9b3021f97b85c4c166e0d37f7a32dfbdb8955cb1816e67efa1cee38d06aec',
                                            'function': 'main',
                                            'occurrence': 1,
                                            'original_end_line': 2037,
                                            'original_start_line': 2014,
                                            'source': 'def main(*a, **k):\n'
                                                      '    _snimok = _v135_snimok()\n'
                                                      '    _itog = _v135_main_ishodnyy(*a, **k)\n'
                                                      '    _horosho, _slovo = _v135_proverka()\n'
                                                      '    try:\n'
                                                      '        with io.open(os.path.join(BAZA_DIR, '
                                                      '"publikaciya_log.txt"), "a",\n'
                                                      '                     encoding="utf-8") as '
                                                      '_f:\n'
                                                      '            _f.write("%s  %s  %s\\n" % '
                                                      '(time.strftime("%Y-%m-%d %H:%M:%S"),\n'
                                                      '                                       '
                                                      '"PASS" if _horosho else "FAIL", _slovo))\n'
                                                      '    except Exception:\n'
                                                      '        pass\n'
                                                      '    if _horosho:\n'
                                                      '        print("  публикация проверена: %s" '
                                                      '% _slovo)\n'
                                                      '    else:\n'
                                                      '        print("  ПУБЛИКАЦИЯ ОТМЕНЕНА: %s" % '
                                                      '_slovo)\n'
                                                      '        for _put, _tekst in '
                                                      '_snimok.items():\n'
                                                      '            try:\n'
                                                      '                with io.open(_put, "w", '
                                                      'encoding="utf-8") as _f:\n'
                                                      '                    _f.write(_tekst)\n'
                                                      '            except Exception:\n'
                                                      '                pass\n'
                                                      '        if _snimok:\n'
                                                      '            print("  рабочие страницы '
                                                      'возвращены в прежний вид")\n'
                                                      '    return _itog\n'},
                                           {'ast_sha256': '6f222421e2001dcffb9eb922ae3d2be9b5dcddc7ed2789fdc775ff939fcdefc2',
                                            'extracted_sha256': '25417047c32ed9468cea6258aa5352a5ce5f511357229696bc7c0063e2a43dab',
                                            'function': 'main',
                                            'occurrence': 2,
                                            'original_end_line': 2085,
                                            'original_start_line': 2068,
                                            'source': 'def main(*a, **k):\n'
                                                      '    _bedy = _v157_net_fajlov()\n'
                                                      '    if _bedy:\n'
                                                      '        _stroka = ("%s  ОТМЕНА СБОРКИ  нет '
                                                      'файлов для записей ready: %d · %s"\n'
                                                      '                   % '
                                                      '(time.strftime("%Y-%m-%d %H:%M:%S"), '
                                                      'len(_bedy),\n'
                                                      '                      "; '
                                                      '".join(_bedy[:5])))\n'
                                                      '        try:\n'
                                                      '            with '
                                                      'io.open(os.path.join(BAZA_DIR, '
                                                      '"publikaciya_log.txt"), "a",\n'
                                                      '                         encoding="utf-8") '
                                                      'as _f:\n'
                                                      '                _f.write(_stroka + "\\n")\n'
                                                      '        except Exception:\n'
                                                      '            pass\n'
                                                      '        print("  СБОРКА ОТМЕНЕНА: не '
                                                      'хватает файлов — %d" % len(_bedy))\n'
                                                      '        for _s in _bedy[:10]:\n'
                                                      '            print("     " + _s)\n'
                                                      '        print("  рабочие страницы оставлены '
                                                      'как есть, запустите v155.py для '
                                                      'восстановления")\n'
                                                      '        return None\n'
                                                      '    return _v157_main_do(*a, **k)\n'}],
                             'original_source_sha256': '2794f01c00a49f1a55c66f3e6af4657808f857e9167f59a5da84c9b8430d724a'}}}
